### ISSUE TITLE
puppet run always exitcode 2 on puppetserver

### ISSUE THREAD

**Issue by aba-rechsteiner** [fraenki/puppet-acme#16]
since we have been using this module we have an exitcode 2 at every puppet run on the puppetserver.

**Comment by fraenki** [comment]
@aba-rechsteiner Some basic details about your configuration, setup, etc. and some logs would be nice :)

**Comment by aba-rechsteiner** [comment]
Hi, our config looks like this:
Module-Version: 1.0.3
OS: Debian 9.11
Puppet: 6.10.1-1stretch

```
acme::accounts:
  - "certmaster@example.com"
acme::profiles:
  dnsimple:
    options:
      dnssleep: 10
    challengetype: 'dns-01'
    hook: 'dnsimple'
    env:
      DNSimple_OAUTH_TOKEN: '<api-token>'

acme::certificates:
  "%{::hostname}.%{::location}.example.com *.example.com":
    use_profile: 'dnsimple'
    use_account: "certmaster@example.com"
    letsencrypt_ca: 'production'
```

there are no logs and there is no output on the puppetrun, just the return code of "puppet agent -t" is always 2. I have no idea how to debug this. Do you have any tips?
